name: Continuous Delivery #nome do workflow
on:
  push:
    branches:
      - main

jobs:
  deliver: #nome do job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code #Check Out do nosso repositorio
        uses: actions/checkout@v5

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v7
        with:
          name: projetozipado #nome do arquivo
          path:
            .

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses : actions/upload-artifact@v7
        with:
         name: projetozipado
      - name: Display structure of downloaded files
        run: ls -R